Fix the menu toggle #1080
nextcloud/bookmarks pull request #1081
Opened 2020-06-19 09:31 UTC by weeman1337

* Fix the menu toggle
* Fix some pixel misalignment in the breadcrumb bar
* Tested on desktop and mobile
* Tested with Nextcloud 19 and 20

closes #1080

![image](https://user-images.githubusercontent.com/6216686/85118157-3c626380-b220-11ea-9166-4289e3eede12.png)

2020-06-19 13:35 UTC, marcelklehr requested changes

2020-06-19 13:35 UTC, marcelklehr commented on src/components/Breadcrumbs.vue
> -	position: fixed;
I'd like to keep this, the breadcrumbs will be scrolled out of screen otherwise.

2020-06-19 15:26 UTC, weeman1337 commented on src/components/Breadcrumbs.vue
> -	position: fixed;
Done. Required some more CSS frickeling, because `position: fixed;` was actually the point why it overlaps.

2020-06-19 15:27 UTC, weeman1337 commented
Additionally fixes the checkbox and "three dots" alignment:
![image](https://user-images.githubusercontent.com/6216686/85149860-15bd2080-b252-11ea-8c6c-e5965a98f960.png)

2020-06-19 17:30 UTC, marcelklehr commented
Awesome!

Can you also fix this while you're at it? My CSS skills seem to be too bad for this :/


![image](https://user-images.githubusercontent.com/986878/85163522-3b065a80-b263-11ea-949e-aa70bf8f64b8.png)

2020-06-19 19:37 UTC, weeman1337 commented on src/components/Bookmark.vue
> +		<a
This makes the bookmark work like a link in grid view.

2020-06-19 19:37 UTC, weeman1337 commented on src/components/Bookmark.vue
> +	margin: 0 3px 3px 3px;
Fixes the checkbox size. At the moment it has unequal white space.

2020-06-19 19:39 UTC, weeman1337 commented on src/components/Breadcrumbs.vue
> +	position: absolute;
I change the bookmark list to be scrollable instead of the entire app content.  
Now the menus on each side reduce the site of the entire app content.

- no overlapping
- left/right menu shift the content

2020-06-19 19:39 UTC, weeman1337 commented on src/components/Breadcrumbs.vue
> +	padding: 5px 7px;
Aligns the text

2020-06-19 19:40 UTC, weeman1337 commented on src/components/BookmarksList.vue
> +	gap: 10px;
Some grid view fine tuning

2020-06-19 19:41 UTC, weeman1337 commented
@marcelklehr please have another look.

2020-06-20 08:56 UTC, marcelklehr commented on src/components/BookmarksList.vue
> +	height: calc(100vh - 50px - 50px);
Can you add `align-content: flex-start;` to fix spreading of content?

2020-06-20 08:56 UTC, marcelklehr commented
Aaah, looks great. Thank you so much :)

2020-06-20 17:02 UTC, merged