Addition of recycle bin for undeleting bookmarks and folders
nextcloud/bookmarks pull request #1402
Opened 2021-02-03 00:13 UTC by DeathByDenim

This is a work-in-progress pull request. This pull requests currently supports deleting and undeleting bookmarks and root-level folders. Intended to address issue #681.

Things that don't work yet:
- Count of deleted bookmarks if a folder is deleted
- Deleting a subfolder only marks it as deleted, but it remains visible
- Clicking on a folder in deleted bookmark changes trash can icon to home icon
- Shares are completely unaccounted for

2021-02-03 10:21 UTC, marcelklehr commented
Awesome!

Here are some thoughts, without having seen the code:

> Count of deleted bookmarks if a folder is deleted

This is tricky. Deleting a folder could mark all descendant bookmarks as deleted as well, but bookmarks can potentially be in multiple folders.

> Deleting a subfolder only marks it as deleted, but it remains visible

This is probably due to the tree entry for said folder. It would be necessary to remove that as well for both bookmarks and folders to not litter the tree with deleted items. In order to still store the old parent somewhere we should probably introduce a trashbin table `trashbin(type, id, parent_folder)`

> Clicking on a folder in deleted bookmark changes trash can icon to home icon

I see. I'm not sure if we actually need that behavior. At least for now it would probably enough to just list the deleted folders without being able to enter them. Otherwise people might be confused about whether if the folder their browsing is deleted or not.

> Shares are completely unaccounted for

So, the behavior we want here would probably be: When a folder is deleted, remove all its shares and public links.

2021-02-04 01:54 UTC, DeathByDenim commented
> > Count of deleted bookmarks if a folder is deleted
> 
> This is tricky. Deleting a folder could mark all descendant bookmarks as deleted as well, but bookmarks can potentially be in multiple folders.

Indeed, I had noticed that bookmarks could exist in multiple folder, but until you pointed this out, it hadn't occurred to me that this will making counts even more difficult.
> 
> > Deleting a subfolder only marks it as deleted, but it remains visible
> 
> This is probably due to the tree entry for said folder. It would be necessary to remove that as well for both bookmarks and folders to not litter the tree with deleted items. In order to still store the old parent somewhere we should probably introduce a trashbin table `trashbin(type, id, parent_folder)`

Oh, I see. Yes, that would be a nice solution. I'll look into that.
> 
> > Clicking on a folder in deleted bookmark changes trash can icon to home icon
> 
> I see. I'm not sure if we actually need that behavior. At least for now it would probably enough to just list the deleted folders without being able to enter them. Otherwise people might be confused about whether if the folder their browsing is deleted or not.
It would be handy to know for a user what is inside of a folder before deleting it permanently. However, we can make this a separate addition and get this working first.
> 
> > Shares are completely unaccounted for
> 
> So, the behavior we want here would probably be: When a folder is deleted, remove all its shares and public links.
Yes, my thoughts exactly. Restoring a folder might have unexpected results for a user as the shares wouldn't be restored though. Then again, it may also be unexpected if unintended sharing occurs since there is no explicit sharing action performed by the user.

Thanks! This is helpful.

2021-02-10 13:19 UTC, marcelklehr requested changes

2021-02-10 13:19 UTC, marcelklehr commented on appinfo/routes.php
> +		['name' => 'internal_bookmark#delete_bookmark_permanently', 'url' => '/bookmark/permanent/{id}', 'verb' => 'DELETE'],
can we change the URI for this to `DELETE /bookmark/{id}?permanent=true`

2021-02-10 13:19 UTC, marcelklehr commented on appinfo/routes.php
> +		['name' => 'internal_bookmark#restore_bookmark', 'url' => '/bookmark/restore/{id}', 'verb' => 'PUT'],
...and this one to `POST /bookmark/{id}/restore`

2021-02-10 13:19 UTC, marcelklehr commented on appinfo/routes.php
> +		['name' => 'internal_folders#get_folders_with_deleted', 'url' => '/folder/withdeleted', 'verb' => 'GET'],
This should be a Query param as well.

2021-02-10 13:19 UTC, marcelklehr commented on l10n/nl.js
> +    "Search" : "Zoeken",
Translations are handled on transifex.com. These will likely be overriden :/

2021-02-10 13:19 UTC, marcelklehr commented on lib/Controller/FoldersController.php
> +			$this->bookmarks->delete($bookmarkId);
This is possibly confusing/fragile, as bookmarks that are in multiple folders would be inside and outside the trashbin at the same time.

2021-02-11 03:15 UTC, DeathByDenim commented on appinfo/routes.php
> +		['name' => 'internal_bookmark#delete_bookmark_permanently', 'url' => '/bookmark/permanent/{id}', 'verb' => 'DELETE'],
I'm not sure if this is possible. I don't see anything about GET parameters like that in https://docs.nextcloud.com/server/latest/developer_manual/basics/routing.html, nor do I see any URI with `?` in the default Nextcloud apps.
Using `?permanent=true` is simply ignored and the method `internal_bookmark#delete_bookmark` is called instead without any way of grabbing the `permanent` parameter that I can see.
Is there a way to do this?

2021-02-11 03:15 UTC, DeathByDenim commented on appinfo/routes.php
> +		['name' => 'internal_bookmark#restore_bookmark', 'url' => '/bookmark/restore/{id}', 'verb' => 'PUT'],
Done

2021-02-11 03:22 UTC, DeathByDenim commented on l10n/nl.js
> +    "Search" : "Zoeken",
Ah oops. Oh well, I undid that.

2021-02-11 03:48 UTC, DeathByDenim commented on lib/Controller/FoldersController.php
> +			$this->bookmarks->delete($bookmarkId);
True, it's tricky that these bookmarks can exist in multiple places. I hadn't thought of that when I initially started this.

I guess your suggestion of a new table `trashbin` would be a better fit for this. This would replace the need for the `deleted` flag I have been using so far for bookmarks and folders. Although that wouldn't solve the confusion aspect of bookmarks existing in both the trashbin and outside. Schrödinger's bookmarks, I suppose!

It would probably make the most sense to have them appear in the trashbin since there were deleted from a certain folder, even if the bookmark may still exist in another folder. They were deleted after all. Not sure what to do if two such bookmarks would have been deleted though. It will only show one in the trashbin. How does one restore that? Two could be shown, I suppose but then the original parent folder would have to be indicated somehow. That might work.

2021-02-11 15:05 UTC, marcelklehr commented on appinfo/routes.php
> +		['name' => 'internal_bookmark#delete_bookmark_permanently', 'url' => '/bookmark/permanent/{id}', 'verb' => 'DELETE'],
You can add a $permanent parameter to delete_bookmark and check that. It gets populated with GET parameters

2021-02-14 21:17 UTC, DeathByDenim commented on appinfo/routes.php
> +		['name' => 'internal_folders#get_folders_with_deleted', 'url' => '/folder/withdeleted', 'verb' => 'GET'],
Done

2021-02-14 21:18 UTC, DeathByDenim commented on appinfo/routes.php
> +		['name' => 'internal_bookmark#delete_bookmark_permanently', 'url' => '/bookmark/permanent/{id}', 'verb' => 'DELETE'],
Thanks, that worked!

2021-02-15 20:01 UTC, marcelklehr commented
I think, it would probably sanest to do the following:

Only put a bookmark in the trash if there are no references left in any non-trashed folders. When deleting a folder, move it from its parent folder into the trash bin, keeping all descendants intact. Any descendant bookmarks of the trashed folder, should be checked for whether they are still in other folders that are non-trashed, if they are not, mark those bookmarks as deleted. When restoring a folder, check if any descendant bookmarks have to be revived. When deleting a bookmark directly, mark it as deleted as well, but also put it in the trash bin.

@DeathByDenim What do you think? Are there any loopholes in this?

2021-02-15 21:41 UTC, DeathByDenim commented
Hi @marcelklehr ,

Yes, that would work. I do see one loophole though.

There could be a situation where a user deletes a bookmark that also exists in another non-trashed folder and they want to restore it. Since a bookmark won't appear in the trash if there are still references to it, it's not possible to restore that bookmark unless the same bookmark is removed from the other folder as well. (Unless I misunderstood you)

Probably the best way to handle this is to put the deleted bookmark in the trash bin immediately, even if there are still references to it in other folders. Then when permanently deleting the entry from the trash bin, only remove that item from `bookmarks_tree` and leave the other entries intact. That way, a user could always restore a bookmark they just deleted.

A side effect of this is that if a user deletes the same bookmark from both folder A as well as B, it would appear once in the trash bin, but restoring it would restore to both folders A and B. That's probably fine though, since if they wanted to restore only in A, they can delete the bookmark from folder B again and then permanently delete it.

2021-02-16 12:38 UTC, marcelklehr commented
Ah yes. So:

When deleting a folder, move it from its parent folder into the trash bin, keeping all descendants intact. Any descendant bookmarks of the trashed folder, should be checked for whether they are still in other folders that are non-trashed, if they are not, mark those bookmarks as deleted. When restoring a folder, check if any descendant bookmarks have to be revived. When deleting a bookmark directly, put it in the trash bin along with the folder it was deleted from (possibly requires two different trash bin tables). When no alive references to a bookmark are left, mark the bookmark as deleted.

2021-02-16 23:56 UTC, DeathByDenim commented
Ok, that makes sense. Who knew this would be so complicated! :)

2021-03-13 13:57 UTC, radoeka commented
What's needed to finish the merger?

2021-03-13 14:11 UTC, DeathByDenim commented
I went on a bit of a detour by giving bookmarks a "deleted" flag, but that failed to account for the fact that the same bookmark can exist in multiple folders. So I'm in to process of moving that "deleted" flag to bookmarks_tree instead. That seems to work, but I still need to fix permanently deleting a bookmark and I haven't tackled the shares yet. Getting there though.

After that, there is the testing!

2021-03-13 14:13 UTC, radoeka commented
@DeathByDenim :)

2024-06-01 08:32 UTC, closed without merging