Add "Copy to" action for bookmarks
nextcloud/bookmarks pull request #1651
Opened 2021-09-18 19:17 UTC by Artem4590

Signed-off-by: Artem Lavrukhin <lavryha4590@gmail.com>

2021-09-19 10:04 UTC, marcelklehr requested changes
Thank you for this contribution! The code is very well written and blends in with the existing code smoothly. :+1:

From a UX perspective, however, I'm not sold on calling this action "copy", as the bookmarks identity will stay the same and editing the "copied" bookmarks will change the original bookmarks as well.

2021-09-19 10:04 UTC, marcelklehr commented on src/store/actions.js
> +					folder.parent_folder = folderId
This does not copy the folder. This should either be a real deep copy or the copy action shouldn't be available when folders are selected.

2021-09-19 10:04 UTC, marcelklehr commented on src/components/CopyDialog.vue
> +						'Copyng %n folder and some bookmarks',
Typo: "Copying"

2021-09-20 11:19 UTC, marcelklehr commented
After a quick discussion with the design team, I'd preferably call this "Add to folders"

2021-09-20 13:28 UTC, marcelklehr commented on src/components/BulkEditing.vue
> +			<ActionButton v-if="!selectedFolders.length" close-after-click @click="onBulkCopy">
:+1:

2021-09-20 13:43 UTC, marcelklehr approved these changes

2021-09-20 14:17 UTC, Artem4590 commented
Do I need to rename everything else to "Add to folders" ?

2021-09-20 14:23 UTC, marcelklehr commented
> Do I need to rename everything else to "Add to folders" ?

I think it's fine if we call it copy in the code, as long as the UI is clear.

2021-09-20 15:20 UTC, Artem4590 commented
Sorry, the order in my name was not correct. Fix in this commit ☝🏻

2021-09-20 15:42 UTC, merged