fixes #416
nextcloud/bookmarks pull request #417
Opened 2017-12-30 05:28 UTC by damko

the route
    array('name' => 'internal_bookmark#edit_bookmark', 'url' => '/bookmark/{id}', 'verb' => 'PUT'),
intercepts all the calls having an additional URL segment like /bookmark/export therefore editBookmark receives "export" as input and obviously returns failure without hitting the right controller method.

As I fix I moved down the routes having the parameter {id} so that the other routes like /bookmark/export or /bookmark/click can match before processing the routes with parameter.

I'm not sure this is the best fix. Another way, out of the top of my head, could be to rename the endpoint as `export_bookmarks` but this would break old clients.

2017-12-30 15:59 UTC, marcelklehr requested changes
Other than the comments, looks good.

2017-12-30 15:59 UTC, marcelklehr commented on js/bookmarks.js
> -	for (var i = 0, len = tags.length; i < len; ++i) {
this change is a noopo, no?

2017-12-30 15:59 UTC, marcelklehr commented on css/bookmarks.css
>  li.tag_list a {
these css changes should go into a separate pr.

2018-01-05 20:12 UTC, blizzz commented on controller/lib/bookmarks.php
> +		if(!is_string($line)) return array();
please always  use curly brackets

2018-01-10 13:07 UTC, marcelklehr commented
@damko Can you update this pr?

2018-01-26 22:31 UTC, blizzz commented
is continued in #421  and #422 → closing

2018-01-26 22:31 UTC, closed without merging