UI: Don't escape URL for editing a bookmark
nextcloud/bookmarks pull request #420
Opened 2018-01-10 16:55 UTC by marcelklehr

fixes #401

2018-01-15 22:09 UTC, blizzz requested changes
The edit check does not work anymore: if you bookmark the site the second time the bookmarklet should show a warning that you are editing an existing bookmark. But it is not happening, actually the second attempt is totally lost. I don't even get log output. network console reports a 200.

2018-01-15 22:12 UTC, marcelklehr commented
mmh. are you sure that is new?

2018-01-18 20:01 UTC, marcelklehr commented
I cannot reproduce this problem with neither this branch nor master... see #429

2018-01-26 22:36 UTC, blizzz commented
@marcelklehr i have the same issue on master with https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propri%C3%A9taires, but just with ascii-domains it works. So, a bug, but not regression.

2018-01-26 22:37 UTC, blizzz approved these changes

2018-01-26 22:37 UTC, merged