Rewrite Client-side: Backbone -> Vue
nextcloud/bookmarks pull request #774
Opened 2019-08-20 18:37 UTC by marcelklehr

2019-08-26 00:14 UTC, marcelklehr commented
![Bookmarks - Nextcloud (5)](https://user-images.githubusercontent.com/986878/63657925-d72c1600-c7a6-11e9-8ec0-d16f8ea32cbf.png)
![Bookmarks - Nextcloud (4)](https://user-images.githubusercontent.com/986878/63657926-d72c1600-c7a6-11e9-8ffe-f1a9ff32638f.png)
![Bookmarks - Nextcloud (3)](https://user-images.githubusercontent.com/986878/63657927-d72c1600-c7a6-11e9-9ce1-c0720a7e8a74.png)
![Bookmarks - Nextcloud (2)](https://user-images.githubusercontent.com/986878/63657928-d7c4ac80-c7a6-11e9-9aec-909114431b1a.png)
![Bookmarks - Nextcloud (1)](https://user-images.githubusercontent.com/986878/63657929-d7c4ac80-c7a6-11e9-8174-e6cad2c0e686.png)

/cc @nextcloud/designers -- Feedback appreciated :)

2019-08-26 08:31 UTC, skjnldsv commented on webpack.common.js
> +		new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
Are you using moment?

2019-08-26 08:32 UTC, skjnldsv commented on src/router.js
> +	base: OC.generateUrl('/apps/bookmarks'),
Use https://github.com/ChristophWurst/nextcloud-router/ :)

`import { generateUrl } from 'nextcloud-router'`

2019-08-26 08:32 UTC, skjnldsv commented on src/main.js
> +	render: h => h(App)
indentation

2019-08-26 08:33 UTC, skjnldsv commented on src/main.js
> +import { Tooltip } from 'nextcloud-vue';
If you want to be lighter, you can import the directive only, it should avoid importing the full library. `import Tooltip from 'nextcloud-vue/dist/Directives/Tooltip'`

2019-08-26 08:35 UTC, skjnldsv commented on src/main.js
> +import '@babel/polyfill/noConflict';
You should not need babel polyfill anymore when using babel preset-env :)

2019-08-26 08:35 UTC, skjnldsv commented on src/components/ViewPrivate.vue
> +#app-content {
You should not need to specify width here, what was the issue you faced?

2019-08-26 08:53 UTC, skjnldsv commented on src/components/ViewPrivate.vue
> +			return this.$store.state.tags;
@nextcloud/vue what do you think about this (accessing state directly) and not using getters?

2019-08-26 08:55 UTC, skjnldsv commented on src/components/TreeFolder.vue
> +.Bookmarks__TreeFolder__Title {
Please no caps in classes :)
Also, if you can, we usually use BEM syntax on our vue library, contacts... It looks pretty good I think, what do you think? :wink:

2019-08-26 08:56 UTC, skjnldsv commented on src/components/Settings.vue
> +			await this.$store.dispatch(actions.DELETE_BOOKMARKS);
I like the actions constants! :+1:

2019-08-26 08:57 UTC, skjnldsv commented on src/components/SidebarBookmark.vue
> +					:value="tags"
indentation

2019-08-26 08:57 UTC, skjnldsv commented on src/components/SidebarBookmark.vue
> +					:limit="7"
indentation

2019-08-26 08:57 UTC, skjnldsv commented on src/components/SidebarBookmark.vue
> +						<span>{{ option | tagLabel }}</span>
Not needed as fixed in the library already :)

2019-08-26 08:58 UTC, skjnldsv commented on src/components/Settings.vue
> +			window.location =
Seems like a job for this.$router? :)

2019-08-26 08:59 UTC, skjnldsv commented on src/components/Settings.vue
> +			return `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('${bookmarkletUrl}?output=popup&url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.sc
This seems like a bad thing to do :thinking: 
Please use @click :)

2019-08-26 08:59 UTC, skjnldsv commented on src/components/Navigation.vue
> +			this.$store.commit(
indentation

2019-08-26 09:00 UTC, skjnldsv commented on src/components/Breadcrumbs.vue
> +	name: 'Breadcrumbs',
This deserves to have its component in the vue library :)
Could you create it there? :rocket:

2019-08-26 09:01 UTC, skjnldsv commented on src/components/BookmarksListFolder.vue
> +	created() {},
Unneeded?

2019-08-26 09:02 UTC, skjnldsv commented on package.json
> +		"uuid": "^3.3.2",
Unused?

2019-08-26 09:06 UTC, skjnldsv commented on .eslintrc.js
> +		//'plugin:vue/recommended',
Needed :)
Also, please enable `plugin:nextcloud/recommended` https://github.com/skjnldsv/vueexample/blob/b16df62098ecd647b1f4300c1e5b889f92d48ef1/.eslintrc.js#L28

2019-08-26 09:06 UTC, ChristophWurst commented on src/components/Settings.vue
> +			return `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('${bookmarkletUrl}?output=popup&url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.sc
> Please use @click :)

nice @mention

2019-08-26 09:06 UTC, skjnldsv requested changes
Great work!!
I did a first pass, don't hesitate to ask if I did a mistake! :wink: 

I see a lot of indentations issues, Did you do a lint fix before pushing?

Also, the icons in the breadcrumbs are too small, are you using the Actions component? :)

2019-08-26 11:32 UTC, marcelklehr commented on src/components/Settings.vue
> +			return `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('${bookmarkletUrl}?output=popup&url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.sc
Ah, this is not supposed to be run in the current window context. It's a bookmarklet URL. You drag the bookmarklet into your browser toolbar ;)

2019-08-26 11:35 UTC, marcelklehr commented
I'm aware of the indentation/styling issues. This is mostly because I'm using prettier, which seems to conflict with lots of styling related eslint rules :/ It Would be really great to have both, but I couldn't bring myself to sort this out just yet :)

2019-08-26 11:41 UTC, marcelklehr commented on src/components/ViewPrivate.vue
> +#app-content {
![image](https://user-images.githubusercontent.com/986878/63688245-1e49f380-c807-11e9-8c29-ed5253526d37.png)

vs 

![image](https://user-images.githubusercontent.com/986878/63688268-2b66e280-c807-11e9-89f8-0c493a297de3.png)

2019-08-26 11:44 UTC, marcelklehr commented on src/components/TreeFolder.vue
> +.Bookmarks__TreeFolder__Title {
Sure, I'm not really a css guru :)

2019-08-26 11:48 UTC, marcelklehr commented
> Also, the icons in the breadcrumbs are too small, are you using the Actions component? :)

Ah, nope, I am not. Good idea :)

2019-08-26 11:58 UTC, skjnldsv commented on src/components/Settings.vue
> +			return `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('${bookmarkletUrl}?output=popup&url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.sc
Ah, sorry! ):

2019-08-26 11:58 UTC, marcelklehr commented on src/components/Settings.vue
> +			window.location =
This is used to trigger a download, though. I'm not sure if you can do that with $router.

2019-08-26 11:59 UTC, skjnldsv commented on src/components/ViewPrivate.vue
> +#app-content {
Let's leave it like that I'll have a look later :)
Let's create an issue when we'll merge this

2019-08-26 12:59 UTC, marcelklehr commented on src/components/SidebarBookmark.vue
> +						<span>{{ option | tagLabel }}</span>
:tada:

2019-08-26 15:50 UTC, jancborchardt commented
O lala @marcelklehr this looks super cool, great work! :) Really only have some detail feedback:
- [ ] The grid/list view switcher could be just 1 icon, like in Files: showing the view that you will switch to, no button background or border (only on hover) and slightly transparent.
- [ ] The grid view elements could have `border-radius: var(--border-radius);`
- [ ] In grid view, the placement of the tags in the top left looks a bit odd. Not sure, I would probably put them below the title of the element. But maybe it’s ok like it is cause putting them below the title just creates a whole bunch of other questions like how does it look like without them etc. Maybe directly above the title would be good?
- [ ] Get a drink and chill cause that’s some fine work :D

2019-08-26 18:03 UTC, marcelklehr commented
@skjnldsv Thanks for all the helpful input!
@jancborchardt Oooh, the border-radius is beautiful!

I agree somewhat on the tags. They don't seem to fit too well anywhere else, either, though. Here are some options:


![Screenshot from 2019-08-26 19-57-53](https://user-images.githubusercontent.com/986878/63711747-69322e00-c83c-11e9-95a9-715d86bdd37d.png)
![Screenshot from 2019-08-26 19-57-21](https://user-images.githubusercontent.com/986878/63711749-69322e00-c83c-11e9-937c-5bf7ac5997ab.png)
![Screenshot from 2019-08-26 20-01-00](https://user-images.githubusercontent.com/986878/63711746-68999780-c83c-11e9-9377-5a83e1db069e.png)

2019-08-26 18:16 UTC, jancborchardt commented
> ![](https://user-images.githubusercontent.com/986878/63711749-69322e00-c83c-11e9-937c-5bf7ac5997ab.png)

This one is definitely the best, all info in one spot. :) Maybe even make them `opacity:.5`, but might not even be necessary.

2019-08-29 11:30 UTC, skjnldsv commented on src/components/Settings.vue
> +          instanceName: oc_defaults.name
@ChristophWurst do we have something for that on our libs?

2019-08-29 12:03 UTC, marcelklehr commented
Mmmh. @skjnldsv I still have the following result with nextcloud-vue@0.12.1:

![Screenshot from 2019-08-29 13-56-39](https://user-images.githubusercontent.com/986878/63938726-cceb6f80-ca65-11e9-8016-e09f5a552b58.png)

2019-08-29 12:05 UTC, skjnldsv commented
@marcelklehr update to 0.12.2

2019-09-02 16:10 UTC, marcelklehr commented on src/components/Settings.vue
> +          instanceName: oc_defaults.name
I'll take that as a no?

2019-09-02 16:13 UTC, marcelklehr commented
@skjnldsv Would you be amendable to checking out the UX of this new version as well? I'd love to hear your feedback on things like creating and moving bookmarks/folders.

2019-09-02 16:13 UTC, skjnldsv commented
@marcelklehr sure!!
I'll do another pass on the reviews this week :)

2019-09-09 08:59 UTC, skjnldsv commented
Awesome job so far! :)

A few remarks/issues:
- Navigation:
  - Nothing so far: Looks great!
- Settings:
  - When switching to list view, and changing folder, the select is back to grid view despite the ui being list view :)
- Main content:
  - Default tags multiselect should have "select option(s)" as placeholder as we cans select multiple
  - Default list view entry looks really empty, could we add the description inline?
  ![Capture d’écran_2019-09-09_10-51-51](https://user-images.githubusercontent.com/14975046/64517204-279b8b80-d2f0-11e9-9815-5d3b5437c0c0.png)
  - 
- Sidebar:
  - If we're not displaying a preview of the page, and just the icon, we should use the compact view of the sidebar. https://nextcloud-vue-components.netlify.com/#/Components?id=appsidebar
  ![Capture d’écran_2019-09-09_10-47-05](https://user-images.githubusercontent.com/14975046/64517559-ddff7080-d2f0-11e9-80f0-9655a42d29f5.png)
  - Ideally we should display the preview (rich previews like facebook, twitter... etc, is it hard? Maybe for another pr ;) )
  - Sharing tab is empty 
  ![Capture d’écran_2019-09-09_10-48-08](https://user-images.githubusercontent.com/14975046/64517323-692c3680-d2f0-11e9-92aa-66721eef4569.png)
  - If no tags, text in multiselect should give the hint the user can type to add a new tag. https://github.com/nextcloud/server/blob/f27f965ad9e9621c8db6714a72419da046a1b5c4/apps/files_sharing/src/components/SharingInput.vue#L31
   ![Capture d’écran_2019-09-09_10-47-30](https://user-images.githubusercontent.com/14975046/64517342-70ebdb00-d2f0-11e9-956e-9cc87c175edd.png)

2019-09-09 15:36 UTC, marcelklehr commented
> When switching to list view, and changing folder, the select is back to grid view despite the ui being list view :)

Ah, yes, the view mode setting is not quite intuitive, yet. So, the button in the upper right corner allows changing the vie temporarily, while the setting allows changing the default for this, ie. for when you load the page.

2019-09-09 15:47 UTC, marcelklehr commented
> Ideally we should display the preview (rich previews like facebook, twitter... etc, is it hard? Maybe for another pr ;) )

This is already implemented, but it relies on a third-party service, so requires admin set-up

2019-09-09 16:00 UTC, marcelklehr commented
> Default list view entry looks really empty, could we add the description inline?

nice idea! :+1:

2019-09-09 16:02 UTC, marcelklehr commented
> Sharing tab is empty

Yup, this is the next feature :grinning:

2019-09-10 20:15 UTC, jancborchardt commented
> Ah, yes, the view mode setting is not quite intuitive, yet. So, the button in the upper right corner allows changing the vie temporarily, while the setting allows changing the default for this, ie. for when you load the page.

Just like we do it in the Files app, there don’t need to be 2 separate things here, as you see this causes confusion. ;) We only need the toggle on the top right → it at the same time allows you to switch it quickly, and it should be permanent. Makes sense? :)

2019-09-11 12:50 UTC, closed without merging

2019-09-11 12:51 UTC, marcelklehr commented
Thanks for all you feedback :relaxed:

2019-09-11 12:54 UTC, skjnldsv commented
Closed by mistake?

2019-09-11 12:56 UTC, marcelklehr commented
Nope, I merged on the terminal and had to rebase, which presumably confused github.

2019-09-11 12:58 UTC, jancborchardt commented
Heh, was already worried. :D Good stuff @marcelklehr! :cake: